[package]
name = "tinfoil-rust"
version = "0.1.0"
authors = ["Rodrigo Leite <rodrigo@leite.dev>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rusb = "0.5"
dialoguer = "0.5"
byteorder = "1.3.2"
num_enum = "0.4.2"
